import React, { useRef } from 'react';
import { useTermCard } from '../context/TermCardContext';

interface InteractiveTextProps {
  text?: string;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  fallbackLeitura?: string;
}

export default function InteractiveText({ text, children, className, style, fallbackLeitura }: InteractiveTextProps) {
  const { openCard } = useTermCard();
  const containerRef = useRef<HTMLSpanElement>(null);

  const handleClick = (e: React.MouseEvent<HTMLSpanElement>) => {
    e.stopPropagation();
    let target = (e.target as HTMLElement).closest('.interactive-word') as HTMLElement;
    if (!target) {
      target = (e.target as HTMLElement).closest('ruby') as HTMLElement;
    }
    if (!target) return;

    // Clone the target node to prevent altering the live DOM
    const clone = target.cloneNode(true) as HTMLElement;
    // Iteratively remove all <rt> elements (furigana readings)
    const rts = clone.querySelectorAll('rt');
    rts.forEach(rt => rt.remove());
    
    const term = clone.textContent?.trim() || '';
    if (!term) return;

    // Capture coordinates and context
    const x = e.clientX;
    const y = e.clientY;
    
    // Clone the container to remove rt (furigana) elements and get clean text context
    const containerClone = e.currentTarget.cloneNode(true) as HTMLElement;
    const containerRts = containerClone.querySelectorAll('rt');
    containerRts.forEach(rt => rt.remove());
    const fraseCompleta = containerClone.textContent?.trim() || '';

    openCard(term, fraseCompleta, x, y);
  };

  const segmentString = (content: string): React.ReactNode[] => {
    try {
      const segmenter = new (Intl as any).Segmenter('ja', { granularity: 'word' });
      const segments = Array.from(segmenter.segment(content)) as any[];
      return segments.map((seg, idx) => {
        const isJp = /[\u3040-\u309F\u30A0-\u30FF\u4E00-\u9FFF]/.test(seg.segment);
        if (isJp) {
          return (
            <span key={idx} className="interactive-word">
              {seg.segment}
            </span>
          );
        } else {
          return (
            <span key={idx} className="non-interactive" style={{ whiteSpace: 'pre-wrap' }}>
              {seg.segment}
            </span>
          );
        }
      });
    } catch (e) {
      // Fallback in case Intl.Segmenter is not supported by the environment
      return [<span key="fallback" className="non-interactive" style={{ whiteSpace: 'pre-wrap' }}>{content}</span>];
    }
  };

  const parseHtmlToReact = (html: string): React.ReactNode[] => {
    // Preprocess to normalize any malformed ruby tags generated by the AI
    // e.g. <ruby>Kanji</ruby><rt>furigana</rt> -> <ruby>Kanji<rt>furigana</rt></ruby>
    let normalized = html.replace(/<ruby>([\s\S]*?)<\/ruby>\s*<rt>([\s\S]*?)<\/rt>/gi, '<ruby>$1<rt>$2</rt></ruby>');

    // Normalize empty rubies and strip non-ruby HTML tags to prevent segmenting HTML syntax
    let cleanedHtml = normalized.replace(/<ruby>([^<]*?)<\/ruby>/g, '$1');
    cleanedHtml = cleanedHtml.replace(/<(?!ruby\b|\/ruby\b|rt\b|\/rt\b|rp\b|\/rp\b|w\b|\/w\b)[^>]+>/gi, '');

    const hasW = cleanedHtml.toLowerCase().includes('<w>') || cleanedHtml.toLowerCase().includes('</w>');

    if (hasW) {
      const parts: React.ReactNode[] = [];
      const wRegex = /(<w>[\s\S]*?<\/w>)/gi;
      const splitW = cleanedHtml.split(wRegex);

      splitW.forEach((part, index) => {
        const trimmedPart = part.trim();
        if (trimmedPart.toLowerCase().startsWith('<w>') && trimmedPart.toLowerCase().endsWith('</w>')) {
          const innerContent = part.replace(/^<w>|<\/w>$/gi, '');
          // Parse any ruby tags inside the <w> tag
          const innerNodes = parseHtmlToReact(innerContent);
          parts.push(
            <span key={`w-${index}`} className="interactive-word">
              {innerNodes}
            </span>
          );
        } else if (part) {
          parts.push(
            <span key={`text-${index}`} className="non-interactive" style={{ whiteSpace: 'pre-wrap' }}>
              {part}
            </span>
          );
        }
      });
      return parts;
    }

    const parts: React.ReactNode[] = [];
    const regex = /(<ruby>[\s\S]*?<\/ruby>)/gi;
    const splitParts = cleanedHtml.split(regex);
    
    splitParts.forEach((part, index) => {
      const trimmedPart = part.trim();
      if (trimmedPart.toLowerCase().startsWith('<ruby>') && trimmedPart.toLowerCase().endsWith('</ruby>')) {
        const rubyMatch = /<ruby>([\s\S]*?)<rt>([\s\S]*?)<\/rt><\/ruby>/i.exec(trimmedPart);
        if (rubyMatch) {
          const kanji = rubyMatch[1].trim();
          const reading = rubyMatch[2].trim();
          parts.push(
            <ruby key={`ruby-${index}`}>
              {kanji}
              <rt>{reading}</rt>
            </ruby>
          );
        } else {
          parts.push(<span key={`raw-html-${index}`} dangerouslySetInnerHTML={{ __html: part }} />);
        }
      } else if (part) {
        parts.push(part);
      }
    });
    
    return parts;
  };

  const processNode = (node: React.ReactNode): React.ReactNode => {
    if (typeof node === 'string') {
      return segmentString(node);
    }
    if (React.isValidElement(node)) {
      return node;
    }
    return node;
  };

  const containerStyle: React.CSSProperties = {
    ...style,
    cursor: 'text',
    display: 'inline'
  };

  let textToUse = text;
  if (text && fallbackLeitura && text !== fallbackLeitura && /[\u4e00-\u9faf]/.test(text) && !text.includes('<ruby>') && !text.includes('<w>')) {
    textToUse = `<ruby>${text}<rt>${fallbackLeitura}</rt></ruby>`;
  }

  let contentNode: React.ReactNode = null;
  if (textToUse !== undefined) {
    const hasW = textToUse.toLowerCase().includes('<w>') || textToUse.toLowerCase().includes('</w>');
    if (!hasW) {
      contentNode = parseHtmlToReact(textToUse).map(processNode);
    } else {
      contentNode = parseHtmlToReact(textToUse);
    }
  } else if (children !== undefined) {
    contentNode = React.Children.map(children, processNode);
  }

  return (
    <span 
      ref={containerRef}
      className={`interactive-text-container ${className || ''}`}
      style={containerStyle}
      onClick={handleClick}
    >
      {contentNode}
    </span>
  );
}
